apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adm
subjects:
  - kind: ServiceAccount
    name: adm
    namespace: cluster-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adm
  namespace: cluster-system
  labels:
    app: adm
